---
version: '3.7'
services:
  database:
    container_name: database
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    image: mysql:5.7
    restart: always

  wordpress:
    build:
      context: wp-cli
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    restart: always
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
